"""esquema inicial: usuarios y monedas

Revision ID: ba74a016b044
Revises: 
Create Date: 2026-10-03 19:57:17.207842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba74a016b044'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('monedas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=200), nullable=False),
    sa.Column('valor_texto', sa.String(length=200), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('ceca', sa.String(length=200), nullable=True),
    sa.Column('variante', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('foto_anverso', sa.String(length=500), nullable=True),
    sa.Column('foto_reverso', sa.String(length=500), nullable=True),
    sa.Column('foto_detalle', sa.String(length=500), nullable=True),
    sa.Column('fecha_agregada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pais_norm', sa.String(length=200), nullable=False),
    sa.Column('valor_norm', sa.String(length=200), nullable=False),
    sa.Column('ceca_norm', sa.String(length=200), nullable=False),
    sa.Column('variante_norm', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'pais_norm', 'valor_norm', 'anio', 'ceca_norm', 'variante_norm', name='uq_tipo_por_usuario')
    )
    op.create_index(op.f('ix_monedas_usuario_id'), 'monedas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monedas_usuario_id'), table_name='monedas')
    op.drop_table('monedas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
