"""lecturas ia para cuota diaria

Revision ID: ef7bec6a4a6f
Revises: ba74a016b044
Create Date: 2026-10-03 20:20:47.398066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7bec6a4a6f'
down_revision: Union[str, Sequence[str], None] = 'ba74a016b044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturas_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecturas_ia_creada_en'), 'lecturas_ia', ['creada_en'], unique=False)
    op.create_index(op.f('ix_lecturas_ia_usuario_id'), 'lecturas_ia', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecturas_ia_usuario_id'), table_name='lecturas_ia')
    op.drop_index(op.f('ix_lecturas_ia_creada_en'), table_name='lecturas_ia')
    op.drop_table('lecturas_ia')
    # ### end Alembic commands ###
